### ISSUE TITLE
xc2par: Panic when building for xc2c64a-7-vq100

### ISSUE THREAD

**Issue by miek** [azonenberg/openfpga#130]
When trying to build a simple blinky example for the XC2C64A, I get a panic in engine::do_par:

```
$ cat blinky.v 
module top(led0, clk_);

(* LOC = "FB1_1" *)
output led0;
(* LOC = "FB2_10" *)
input clk_;

wire clk;
BUFG bufg0 (
    .I(clk_),
    .O(clk),
);

reg [8:0] counter;

assign {led0} = counter[8];

always @(posedge clk)
    counter <= counter + 1;
endmodule

$ yosys -p "synth_coolrunner2 -json blinky.json" blinky.v
[...]

$ RUST_BACKTRACE=1 ./target/debug/xc2par -p xc2c64-7-vq100 blinky.json -v
Feb 17 03:36:38.047 INFO cells - processing, type: ANDTERM, cell name: $auto$coolrunner2_sop.cc:143:execute$235, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.048 INFO cells - processing, type: ANDTERM, cell name: $auto$coolrunner2_sop.cc:143:execute$238, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.048 INFO cells - processing, type: ANDTERM, cell name: $auto$coolrunner2_sop.cc:143:execute$241, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.048 INFO cells - processing, type: ANDTERM, cell name: $auto$coolrunner2_sop.cc:143:execute$244, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.049 INFO cells - processing, type: ANDTERM, cell name: $auto$coolrunner2_sop.cc:143:execute$247, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.049 INFO cells - processing, type: ANDTERM, cell name: $auto$coolrunner2_sop.cc:143:execute$250, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.049 INFO cells - processing, type: ANDTERM, cell name: $auto$coolrunner2_sop.cc:143:execute$253, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.049 INFO cells - processing, type: ANDTERM, cell name: $auto$coolrunner2_sop.cc:143:execute$256, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.050 INFO cells - processing, type: MACROCELL_XOR, cell name: $auto$coolrunner2_sop.cc:154:execute$236, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.050 INFO cells - processing, type: MACROCELL_XOR, cell name: $auto$coolrunner2_sop.cc:154:execute$239, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.050 INFO cells - processing, type: MACROCELL_XOR, cell name: $auto$coolrunner2_sop.cc:154:execute$242, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.050 INFO cells - processing, type: MACROCELL_XOR, cell name: $auto$coolrunner2_sop.cc:154:execute$245, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.051 INFO cells - processing, type: MACROCELL_XOR, cell name: $auto$coolrunner2_sop.cc:154:execute$248, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.051 INFO cells - processing, type: MACROCELL_XOR, cell name: $auto$coolrunner2_sop.cc:154:execute$251, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.051 INFO cells - processing, type: MACROCELL_XOR, cell name: $auto$coolrunner2_sop.cc:154:execute$254, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.051 INFO cells - processing, type: MACROCELL_XOR, cell name: $auto$coolrunner2_sop.cc:154:execute$257, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.052 INFO cells - processing, type: ANDTERM, cell name: $auto$coolrunner2_sop.cc:285:execute$260, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.052 INFO cells - processing, type: MACROCELL_XOR, cell name: $auto$coolrunner2_sop.cc:292:execute$261, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.052 INFO cells - processing, type: IBUF, cell name: $auto$iopadmap.cc:403:execute$263, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.052 INFO cells - processing, type: IOBUFE, cell name: $auto$iopadmap.cc:403:execute$265, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.052 INFO cells - processing, type: FDCP, cell name: $auto$simplemap.cc:420:simplemap_dff$51, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.053 INFO cells - processing, type: FTCP, cell name: $extract$\FTCP$217, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.053 INFO cells - processing, type: FTCP, cell name: $extract$\FTCP$218, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.053 INFO cells - processing, type: FTCP, cell name: $extract$\FTCP$219, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.053 INFO cells - processing, type: FTCP, cell name: $extract$\FTCP$220, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.054 INFO cells - processing, type: FTCP, cell name: $extract$\FTCP$221, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.054 INFO cells - processing, type: FTCP, cell name: $extract$\FTCP$222, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.054 INFO cells - processing, type: FTCP, cell name: $extract$\FTCP$223, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.055 INFO cells - processing, type: FTCP, cell name: $extract$\FTCP$224, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.055 INFO cells - processing, type: BUFG, cell name: bufg0, top module: top, pass: yosys -> intermediate
Feb 17 03:36:38.055 INFO intermed2input - adding P-term, inputgraph: 0, intermed: 6, name: $auto$coolrunner2_sop.cc:143:execute$253, pass: intermediate -> input
Feb 17 03:36:38.056 INFO intermed2input - adding XOR bits, inputgraph: 6, intermed: 14, name: $auto$coolrunner2_sop.cc:154:execute$254, pass: intermediate -> input
Feb 17 03:36:38.056 INFO intermed2input - adding input bits, inputgraph: 9, intermed: 18, name: $auto$iopadmap.cc:403:execute$263, pass: intermediate -> input
Feb 17 03:36:38.056 INFO intermed2input - adding BUFG, inputgraph: 0, intermed: 29, name: bufg0, pass: intermediate -> input
Feb 17 03:36:38.056 INFO intermed2input - adding register bits, inputgraph: 6, intermed: 20, name: $auto$simplemap.cc:420:simplemap_dff$51, pass: intermediate -> input
Feb 17 03:36:38.057 INFO intermed2input - adding P-term, inputgraph: 1, intermed: 16, name: $auto$coolrunner2_sop.cc:285:execute$260, pass: intermediate -> input
Feb 17 03:36:38.057 INFO intermed2input - adding XOR bits, inputgraph: 8, intermed: 17, name: $auto$coolrunner2_sop.cc:292:execute$261, pass: intermediate -> input
Feb 17 03:36:38.057 INFO intermed2input - adding register bits, inputgraph: 8, intermed: 21, name: $extract$\FTCP$217, pass: intermediate -> input
Feb 17 03:36:38.057 INFO intermed2input - adding P-term, inputgraph: 2, intermed: 5, name: $auto$coolrunner2_sop.cc:143:execute$250, pass: intermediate -> input
Feb 17 03:36:38.058 INFO intermed2input - adding XOR bits, inputgraph: 5, intermed: 13, name: $auto$coolrunner2_sop.cc:154:execute$251, pass: intermediate -> input
Feb 17 03:36:38.058 INFO intermed2input - adding register bits, inputgraph: 5, intermed: 22, name: $extract$\FTCP$218, pass: intermediate -> input
Feb 17 03:36:38.058 INFO intermed2input - adding P-term, inputgraph: 3, intermed: 4, name: $auto$coolrunner2_sop.cc:143:execute$247, pass: intermediate -> input
Feb 17 03:36:38.058 INFO intermed2input - adding XOR bits, inputgraph: 4, intermed: 12, name: $auto$coolrunner2_sop.cc:154:execute$248, pass: intermediate -> input
Feb 17 03:36:38.059 INFO intermed2input - adding register bits, inputgraph: 4, intermed: 23, name: $extract$\FTCP$219, pass: intermediate -> input
Feb 17 03:36:38.059 INFO intermed2input - adding P-term, inputgraph: 4, intermed: 3, name: $auto$coolrunner2_sop.cc:143:execute$244, pass: intermediate -> input
Feb 17 03:36:38.059 INFO intermed2input - adding XOR bits, inputgraph: 3, intermed: 11, name: $auto$coolrunner2_sop.cc:154:execute$245, pass: intermediate -> input
Feb 17 03:36:38.059 INFO intermed2input - adding register bits, inputgraph: 3, intermed: 24, name: $extract$\FTCP$220, pass: intermediate -> input
Feb 17 03:36:38.060 INFO intermed2input - adding P-term, inputgraph: 5, intermed: 2, name: $auto$coolrunner2_sop.cc:143:execute$241, pass: intermediate -> input
Feb 17 03:36:38.060 INFO intermed2input - adding XOR bits, inputgraph: 2, intermed: 10, name: $auto$coolrunner2_sop.cc:154:execute$242, pass: intermediate -> input
Feb 17 03:36:38.060 INFO intermed2input - adding register bits, inputgraph: 2, intermed: 25, name: $extract$\FTCP$221, pass: intermediate -> input
Feb 17 03:36:38.061 INFO intermed2input - adding P-term, inputgraph: 6, intermed: 1, name: $auto$coolrunner2_sop.cc:143:execute$238, pass: intermediate -> input
Feb 17 03:36:38.061 INFO intermed2input - adding XOR bits, inputgraph: 1, intermed: 9, name: $auto$coolrunner2_sop.cc:154:execute$239, pass: intermediate -> input
Feb 17 03:36:38.061 INFO intermed2input - adding register bits, inputgraph: 1, intermed: 26, name: $extract$\FTCP$222, pass: intermediate -> input
Feb 17 03:36:38.062 INFO intermed2input - adding P-term, inputgraph: 7, intermed: 7, name: $auto$coolrunner2_sop.cc:143:execute$256, pass: intermediate -> input
Feb 17 03:36:38.062 INFO intermed2input - adding XOR bits, inputgraph: 7, intermed: 15, name: $auto$coolrunner2_sop.cc:154:execute$257, pass: intermediate -> input
Feb 17 03:36:38.062 INFO intermed2input - adding register bits, inputgraph: 7, intermed: 27, name: $extract$\FTCP$223, pass: intermediate -> input
Feb 17 03:36:38.063 INFO intermed2input - adding P-term, inputgraph: 8, intermed: 0, name: $auto$coolrunner2_sop.cc:143:execute$235, pass: intermediate -> input
Feb 17 03:36:38.063 INFO intermed2input - adding XOR bits, inputgraph: 0, intermed: 8, name: $auto$coolrunner2_sop.cc:154:execute$236, pass: intermediate -> input
Feb 17 03:36:38.063 INFO intermed2input - adding register bits, inputgraph: 0, intermed: 28, name: $extract$\FTCP$224, pass: intermediate -> input
Feb 17 03:36:38.064 INFO intermed2input - adding IO bits, inputgraph: 0, intermed: 19, name: $auto$iopadmap.cc:403:execute$265, pass: intermediate -> input
Feb 17 03:36:38.064 INFO PAR - total macrocell count, num mcs: 10, pass: PAR
Feb 17 03:36:38.064 INFO PAR - total unique pterm count, num pterms: 9, pass: PAR
Feb 17 03:36:38.064 INFO PAR - total bufg count, num bufg: 1, pass: PAR
Feb 17 03:36:38.065 INFO PAR - total bufgts count, num bufgts: 0, pass: PAR
Feb 17 03:36:38.065 INFO PAR - total bufgsr count, num bufgsr: 0, pass: PAR
Feb 17 03:36:38.065 INFO PAR - forcing global buffer LOC due to IO pad LOC, index: 2, name: bufg0, pass: PAR
Feb 17 03:36:38.065 INFO PAR - placed global buffer (fixed), index: 2, name: bufg0, pass: PAR
Feb 17 03:36:38.065 INFO PAR - placed macrocell (fixed), mc: 0, fb: 0, pininput: false, name: $auto$coolrunner2_sop.cc:154:execute$236_$extract$\FTCP$224_$auto$iopadmap.cc:403:execute$265, pass: PAR
Feb 17 03:36:38.066 INFO PAR - placed macrocell (fixed), mc: 9, fb: 1, pininput: true, name: $auto$iopadmap.cc:403:execute$263, pass: PAR
Feb 17 03:36:38.066 INFO PAR - placed macrocell (free), mc: 1, fb: 0, pininput: false, name: $auto$coolrunner2_sop.cc:154:execute$239_$extract$\FTCP$222, pass: PAR
Feb 17 03:36:38.066 INFO PAR - placed macrocell (free), mc: 2, fb: 0, pininput: false, name: $auto$coolrunner2_sop.cc:154:execute$242_$extract$\FTCP$221, pass: PAR
Feb 17 03:36:38.067 INFO PAR - placed macrocell (free), mc: 3, fb: 0, pininput: false, name: $auto$coolrunner2_sop.cc:154:execute$245_$extract$\FTCP$220, pass: PAR
Feb 17 03:36:38.067 INFO PAR - placed macrocell (free), mc: 4, fb: 0, pininput: false, name: $auto$coolrunner2_sop.cc:154:execute$248_$extract$\FTCP$219, pass: PAR
Feb 17 03:36:38.067 INFO PAR - placed macrocell (free), mc: 5, fb: 0, pininput: false, name: $auto$coolrunner2_sop.cc:154:execute$251_$extract$\FTCP$218, pass: PAR
Feb 17 03:36:38.067 INFO PAR - placed macrocell (free), mc: 6, fb: 0, pininput: false, name: $auto$coolrunner2_sop.cc:154:execute$254_$auto$simplemap.cc:420:simplemap_dff$51, pass: PAR
Feb 17 03:36:38.068 INFO PAR - placed macrocell (free), mc: 7, fb: 0, pininput: false, name: $auto$coolrunner2_sop.cc:154:execute$257_$extract$\FTCP$223, pass: PAR
Feb 17 03:36:38.068 INFO PAR - placed macrocell (free), mc: 8, fb: 0, pininput: false, name: $auto$coolrunner2_sop.cc:292:execute$261_$extract$\FTCP$217, pass: PAR
Feb 17 03:36:38.072 INFO PAR - placement successfully found, pass: PAR
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40
stack backtrace:
[...]
  13: core::panicking::panic
             at src/libcore/panicking.rs:51
  14: core::option::Option<T>::unwrap
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15
  15: xc2par::engine::do_par
             at ./src/engine.rs:1271
  16: xc2par::compiler_driver::xc2par_complete_flow
             at ./src/compiler_driver.rs:172
  17: xc2par::main
             at src/bin/xc2par.rs:198
  18: std::rt::lang_start::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  22: std::panicking::try
             at src/libstd/panicking.rs:270
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: std::rt::lang_start
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

(engine.rs:1271 is `let zia = result_i.unwrap();`)

**Comment by ArcaneNibble** [comment]
Yes, XC2C64A support is incomplete due to concerns regarding the source of the ZIA mapping table. I may have a solution for this that doesn't require a SEM/FIB, stay tuned

**Comment by ArcaneNibble** [comment]
XC2C64A support has been added now! Let me know if it works for you, and feel free to report further bugs.
