### ISSUE TITLE
Uninitialized read

### ISSUE THREAD

**Issue by whitequark** [azonenberg/openfpga#16]
Msan describes it well enough:

```
==12385==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x8b2c55 in Greenpak4BitstreamEntity::GetNetlistEntity() /home/whitequark/Work/openfpga/build/../src/greenpak4/Greenpak4BitstreamEntity.cpp:98:5
    #1 0xc3d20f in Greenpak4PGA::Save(bool*) /home/whitequark/Work/openfpga/build/../src/greenpak4/Greenpak4PGA.cpp:293:51
    #2 0xa61224 in Greenpak4Device::WriteToFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) /home/whitequark/Work/openfpga/build/../src/greenpak4/Greenpak4Device.cpp:578:7
    #3 0x4df9b4 in main /home/whitequark/Work/openfpga/build/../src/gp4par/main.cpp:230:2
    #4 0x7fd6a5f7a5ef in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x205ef)
    #5 0x43ee18 in _start (/home/whitequark/Work/openfpga/build/bin/gp4par+0x43ee18)

  Uninitialized value was stored to memory at
    #0 0x8b2bb7 in Greenpak4BitstreamEntity::GetNetlistEntity() /home/whitequark/Work/openfpga/build/../src/greenpak4/Greenpak4BitstreamEntity.cpp:97:16
    #1 0xc3d20f in Greenpak4PGA::Save(bool*) /home/whitequark/Work/openfpga/build/../src/greenpak4/Greenpak4PGA.cpp:293:51
    #2 0xa61224 in Greenpak4Device::WriteToFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) /home/whitequark/Work/openfpga/build/../src/greenpak4/Greenpak4Device.cpp:578:7
    #3 0x4df9b4 in main /home/whitequark/Work/openfpga/build/../src/gp4par/main.cpp:230:2
    #4 0x7fd6a5f7a5ef in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x205ef)

  Uninitialized value was created by a heap deallocation
    #0 0x4ac414 in operator delete[](void*) (/home/whitequark/Work/openfpga/build/bin/gp4par+0x4ac414)
    #1 0xf15187 in PARGraphNode::~PARGraphNode() /home/whitequark/Work/openfpga/build/../src/xbpar/PARGraphNode.cpp:32:1
    #2 0xed5668 in PARGraph::~PARGraph() /home/whitequark/Work/openfpga/build/../src/xbpar/PARGraph.cpp:33:3
    #3 0xed6a33 in PARGraph::~PARGraph() /home/whitequark/Work/openfpga/build/../src/xbpar/PARGraph.cpp:31:1
    #4 0x6db09e in DoPAR(Greenpak4Netlist*, Greenpak4Device*) /home/whitequark/Work/openfpga/build/../src/gp4par/par_main.cpp:62:2
    #5 0x4deb14 in main /home/whitequark/Work/openfpga/build/../src/gp4par/main.cpp:225:6
    #6 0x7fd6a5f7a5ef in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x205ef)
```

**Comment by whitequark** [comment]
Confirmed as fixed, closing.
